name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - converted_to_draft
    branches:
      - main

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: NPM Install
          run: npm i ci
        - name: Test
          run: npm test
        - name: build
          env:
            GOOGLE_API_KEY: ${{ secrets.GOOGLE_DOCS_API_KEY }}
          run: npm run build